const norm=(s:string)=>(s||'').replace(/\\s+/g,' ').trim().toLowerCase();
const vis=(e:Element)=>{const x=e as HTMLElement,r=x.getBoundingClientRect(),c=getComputedStyle(x);return r.width>0&&r.height>0&&c.display!=='none'&&c.visibility!=='hidden'};
const cs=()=>[...document.querySelectorAll('[role="group"],fieldset,.nsv_survey_item,.nsv_survey_item_inner,form')].filter(vis);
function analyze(){const questions=cs().filter(c=>c.querySelector('input,textarea,select,[contenteditable="true"]')).map((c,index)=>{const h=c.querySelector('[role="heading"],.nsv_survey_reply_question_title,legend');const choices=[...c.querySelectorAll('label,[role="option"],[role="radio"],[role="checkbox"]')].filter(vis).map(x=>(x.textContent||'').replace(/\\s+/g,' ').trim()).filter(Boolean);const inputs=[...c.querySelectorAll('textarea,input:not([type="radio"]):not([type="checkbox"]),select,[contenteditable="true"]')].filter(vis).map(x=>({tag:x.tagName.toLowerCase(),type:(x as HTMLInputElement).type||'',placeholder:(x as HTMLInputElement).placeholder||''}));return{index,question:(h?.textContent||'').replace(/\\s+/g,' ').trim(),inputs,choices:[...new Set(choices)].slice(0,30)}});const buttons=[...document.querySelectorAll('button,[role="button"],input[type="submit"],input[type="button"]')].filter(vis).map(x=>(x.textContent||(x as HTMLInputElement).value||'').replace(/\\s+/g,' ').trim()).filter(Boolean);return{url:location.href,questions,buttons:[...new Set(buttons)].slice(0,30)}}
function find(q:string){const n=norm(q);return cs().filter(c=>norm(c.textContent||'').includes(n)).sort((a,b)=>(a.textContent||'').length-(b.textContent||'').length)[0]||null}
function val(e:HTMLInputElement|HTMLTextAreaElement,v:string){const p=e instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;const set=Object.getOwnPropertyDescriptor(p,'value')?.set;set?set.call(e,v):e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}))}
function choose(root:Element,a:string){const n=norm(a);const l=[...root.querySelectorAll('label')].find(x=>norm(x.textContent||'')===n)||[...root.querySelectorAll('label')].find(x=>norm(x.textContent||'').includes(n));if(!l)return false;(l as HTMLElement).click();return true}
const tpl=(v:any,p:any)=>String(v??'').replaceAll('{{name}}',p?.name||'').replaceAll('{{num}}',p?.num||'').replaceAll('{{phone}}',p?.num||'');
const matches=(template:string)=>{try{const t=new URL(template.replace(/\\{\\{(?:name|num)\\}\\}/g,''),location.href);return t.origin===location.origin&&t.pathname===location.pathname}catch{return location.href.startsWith(template.replace(/\\{\\{(?:name|num)\\}\\}/g,''))}};
async function run(p:any){const f=(p.kit?.forms||[]).find((x:any)=>matches(x.url));if(!f)return{ok:false,message:'현재 페이지와 Kit URL이 일치하지 않습니다.'};for(const s of f.steps||[]){const r=find(s.question||'');if(!r)return{ok:false,message:'문항을 찾지 못했습니다: '+s.question};const a=tpl(s.answer,p);if(['choice','checkbox','agreement'].includes(s.type)){if(!choose(r,a))return{ok:false,message:'선택하지 못했습니다: '+s.question}}else{const e=r.querySelector('textarea,input:not([type="radio"]):not([type="checkbox"]):not([type="hidden"])') as HTMLInputElement|HTMLTextAreaElement|null;if(!e)return{ok:false,message:'입력란을 찾지 못했습니다: '+s.question};val(e,a)}}return{ok:true,message:'입력 완료'}}
chrome.runtime.onMessage.addListener((m,_s,send)=>{if(m.cmd==='analyze'){send(analyze());return}if(m.cmd==='run'){run(m.payload).then(send);return true}if(m.cmd==='get-analysis'){chrome.storage.session.get('lastAnalysis').then(x=>send(x.lastAnalysis||null));return true}});
window.addEventListener('message',e=>{if(e.source!==window||e.data?.source!=='form-routine-kit-web')return;if(e.data.type==='analyze-current-tab')chrome.runtime.sendMessage({cmd:'web-analyze'}).catch(()=>{});if(e.data.type==='prepare'){chrome.storage.session.set({pendingRun:e.data.payload}).then(()=>{window.postMessage({source:'form-routine-kit-extension',type:'status',message:'실행 정보를 저장했습니다.'},'*')}).catch(()=>{})}if(e.data.type==='get-analysis')chrome.runtime.sendMessage({cmd:'get-analysis'}).then(a=>window.postMessage({source:'form-routine-kit-extension',type:'analysis',analysis:a},'*')).catch(()=>{})});
chrome.storage.session.get('pendingRun').then(async x=>{const p=x.pendingRun;if(!p)return;const f=(p.kit?.forms||[]).find((x:any)=>matches(x.url));if(!f)return;const result=await run(p);await chrome.storage.session.remove('pendingRun');window.postMessage({source:'form-routine-kit-extension',type:'status',message:result.message},'*')}).catch(()=>{});