import{useState}from'react';
type Q={index:number;question:string;inputs:any[];choices:string[]};
type B={text:string;type:string;tag:string};
type A={url:string;title:string;questions:Q[];buttons:B[]};
type Step={type:string;question?:string;answer?:string|string[];text?:string;checked?:boolean;nextUrl?:string};
type Form={url:string;title?:string;steps:Step[]};
type Kit={version:number;title:string;forms:Form[]};

const web='https://ninetaild.github.io/form/';
const tpl=(v:any,p:any)=>String(v??'').replaceAll('{{name}}',p?.name||'').replaceAll('{{num}}',p?.num||'');
const save=(name:string,data:any)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click()};

export default function Popup(){
 const[s,setS]=useState('현재 페이지를 읽으면 바로 Kit 편집 화면으로 이어집니다.'),[a,setA]=useState<A|null>(null),[steps,setSteps]=useState<Step[]>([]),[title,setTitle]=useState('새 Form Routine Kit'),[url,setUrl]=useState('');
 const analyze=async()=>{try{const[t]=await chrome.tabs.query({active:true,currentWindow:true});if(!t.id)throw 0;const r=await chrome.tabs.sendMessage(t.id,{cmd:'analyze'});setA(r);setUrl(r?.url||'');setSteps([]);setS('현재 페이지에서 '+(r?.questions?.length||0)+'개 문항과 '+(r?.buttons?.length||0)+'개 버튼을 읽었습니다. 아래에서 편집하세요.')}catch{setS('현재 페이지를 읽을 수 없습니다. 폼 페이지에서 다시 시도하세요.')}};
 const addQ=(q:Q)=>{const type=q.question?.includes('이름')?'name':(q.question?.includes('번호')||q.question?.includes('전화')||q.inputs?.some(i=>i.type==='tel')?'num':q.choices?.length?'choice':'text');setSteps(x=>[...x,{type,question:q.question,answer:type==='name'?'{{name}}':type==='num'?'{{num}}':type==='choice'?(q.choices[0]||''):'',choices:q.choices,checked:true}])};
 const addB=(b:B)=>setSteps(x=>[...x,{type:'action',text:b.text}]);
 const upd=(i:number,p:Partial<Step>)=>setSteps(x=>x.map((v,n)=>n===i?{...v,...p}:v));
 const remove=(i:number)=>setSteps(x=>x.filter((_,n)=>n!==i));
 const build=():Kit=>({version:3,title,forms:[{url:url.trim()||a?.url||'',title:a?.title,steps}]});
 return <main style={{width:390,padding:14,fontFamily:'system-ui'}}><h3>Form Routine Kit</h3><button style={{width:'100%',padding:9}} onClick={()=>chrome.tabs.create({url:web})}>Kit 실행 화면</button><hr/><button style={{width:'100%',padding:10}} onClick={analyze}>① 현재 페이지 읽기</button><p style={{fontSize:12,color:'#555'}}>{s}</p>
 {a&&<><input style={{width:'100%',boxSizing:'border-box',padding:7}} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Kit 이름"/><input style={{width:'100%',boxSizing:'border-box',padding:7,marginTop:6}} value={url} onChange={e=>setUrl(e.target.value)} placeholder="URL ({{name}}, {{num}} 가능)"/><h4>문항 선택</h4>{a.questions.map(q=><div key={q.index} style={{border:'1px solid #ddd',padding:8,margin:'6px 0'}}><label><input type="checkbox" onChange={e=>e.target.checked?addQ(q):setSteps(x=>x.filter(s=>s.question!==q.question))}/> <b>{q.question||'문항 '+(q.index+1)}</b></label><div style={{fontSize:11,color:'#777'}}>{q.choices?.length?'객관식/체크 선택지: '+q.choices.join(' / '):'주관식/입력'} · {q.inputs?.map(i=>i.type||i.tag).join(', ')}</div></div>)}<h4>버튼 선택</h4>{a.buttons.map((b,i)=><div key={i} style={{border:'1px solid #ddd',padding:8,margin:'6px 0'}}><label><input type="checkbox" onChange={e=>e.target.checked?addB(b):setSteps(x=>x.filter(s=>s.type!=='action'||s.text!==b.text))}/> {b.text} <small>({b.tag})</small></label></div>)}<h4>선택된 루틴</h4>{steps.map((s,i)=><div key={i} style={{border:'1px solid #aaa',padding:8,margin:'6px 0'}}><select value={s.type} onChange={e=>upd(i,{type:e.target.value})}><option value="choice">객관식</option><option value="checkbox">체크박스</option><option value="agreement">동의</option><option value="text">텍스트</option><option value="name">{{name}}</option><option value="num">{{num}}</option><option value="action">다음/제출</option></select>{s.type==='action'?<><input value={s.text||''} onChange={e=>upd(i,{text:e.target.value})} placeholder="버튼"/><input value={s.nextUrl||''} onChange={e=>upd(i,{nextUrl:e.target.value})} placeholder="다음 URL (선택)"/></>:s.choices?.length?<select value={Array.isArray(s.answer)?s.answer[0]:s.answer||''} onChange={e=>upd(i,{answer:e.target.value})}>{s.choices.map(x=><option key={x}>{x}</option>)}</select>:<input value={Array.isArray(s.answer)?s.answer.join(','):s.answer||''} onChange={e=>upd(i,{answer:e.target.value})} placeholder="{{name}}, {{num}} 또는 직접 입력"/>}<button onClick={()=>remove(i)}>삭제</button></div>)}<button style={{width:'100%',padding:10}} onClick={()=>save('form-routine-kit.json',build())}>② JSON으로 배포</button></>}</main>