import{useEffect,useState}from'react';

type Kit={file:string;title:string};
type Q={index:number;question:string;inputs:{tag:string;type:string;placeholder:string}[];choices:string[]};
type Button={text:string;type:string;tag:string};
type A={url:string;title:string;questions:Q[];buttons:Button[]};
type Step={type:'choice'|'checkbox'|'agreement'|'text'|'name'|'num'|'action';question?:string;answer?:string;text?:string;checked?:boolean;nextUrl?:string};
type Form={url:string;steps:Step[]};
type KitJson={version:number;title:string;forms:Form[]};

const send=(m:unknown)=>window.postMessage({source:'form-routine-kit-web',...m},'*');
const resolveUrl=(url:string,name:string,num:string)=>String(url||'').replaceAll('{{name}}',encodeURIComponent(name)).replaceAll('{{num}}',encodeURIComponent(num));

export default function App(){
 const[mode,setMode]=useState<'run'|'build'|'json'>('run'),[kits,setKits]=useState<Kit[]>([]),[file,setFile]=useState(''),[name,setName]=useState(''),[num,setNum]=useState(''),[agree,setAgree]=useState(false),[analysis,setAnalysis]=useState<A|null>(null),[urlTemplate,setUrlTemplate]=useState(''),[steps,setSteps]=useState<Step[]>([]),[kitTitle,setKitTitle]=useState('새 Form Routine Kit'),[raw,setRaw]=useState(''),[status,setStatus]=useState('');

 useEffect(()=>{fetch('./kits/index.json',{cache:'no-store'}).then(r=>r.json()).then((x:Kit[])=>{setKits(x);setFile(x[0]?.file||'')}).catch(()=>setStatus('Kit 목록을 불러오지 못했습니다.'));
 const f=(e:MessageEvent)=>{if(e.source!==window||e.data?.source!=='form-routine-kit-extension')return;if(e.data.type==='analysis'){const a=e.data.analysis as A;setAnalysis(a);setUrlTemplate(a?.url||'');setSteps([])}if(e.data.type==='status')setStatus(e.data.message)};addEventListener('message',f);return()=>removeEventListener('message',f)},[]);

 const loadKit=async()=>{try{const k=await fetch('./kits/'+file,{cache:'no-store'}).then(r=>r.json());return k as KitJson}catch{setStatus('Kit JSON을 읽지 못했습니다.');return null}};
 const run=async()=>{const kit=await loadKit();if(!kit?.forms?.length){setStatus('Kit에 실행할 폼이 없습니다.');return}if(!agree){setStatus('안내 내용을 확인해 주세요.');return}const target=resolveUrl(kit.forms[0].url,name.trim(),num.trim());send({type:'prepare',payload:{kit,name:name.trim(),num:num.trim()}});setStatus('Kit을 준비했습니다. 폼을 엽니다.');window.open(target,'_blank','noopener')};
 const analyze=()=>{setStatus('현재 활성 탭의 모든 문항과 버튼을 읽습니다.');send({type:'analyze-current-tab'})};

 const addQuestion=(q:Q)=>{const guess=q.question.includes('이름')?'name':(q.question.includes('번호')||q.question.includes('전화')||q.inputs.some(i=>i.type==='tel')?'num':q.choices.length?'choice':'text') as Step['type'];setSteps(s=>[...s,{type:guess,question:q.question,answer:guess==='name'?'{{name}}':guess==='num'?'{{num}}':guess==='choice'?(q.choices[0]||''):'',checked:true}])};
 const addButton=(b:Button)=>setSteps(s=>[...s,{type:'action',text:b.text}]);
 const updateStep=(i:number,p:Partial<Step>)=>setSteps(s=>s.map((x,n)=>n===i?{...x,...p}:x));
 const removeStep=(i:number)=>setSteps(s=>s.filter((_,n)=>n!==i));
 const buildJson=():KitJson=>({version:3,title:kitTitle,forms:[{url:urlTemplate.trim()||(analysis?.url||''),steps}]});
 const save=()=>{if(!analysis){setStatus('먼저 현재 페이지를 읽어 주세요.');return}const kit=buildJson();const text=JSON.stringify(kit,null,2);setRaw(text);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download='form-routine-kit.json';a.click();setStatus('Kit JSON을 배포용 파일로 저장했습니다.')};
 const applyRaw=()=>{try{const k=JSON.parse(raw) as KitJson;if(!k.forms?.length||!k.forms[0]?.url)throw new Error();setKitTitle(k.title||'Form Routine Kit');setUrlTemplate(k.forms[0].url);setSteps(k.forms[0].steps||[]);setStatus('개발자 JSON을 불러왔습니다.')}catch{setStatus('JSON 형식이 올바르지 않습니다.')}};
 const importJson=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{setRaw(String(rd.result||''));setMode('json')};rd.readAsText(f)};

 return <main className="shell"><header><b>Form Routine Kit</b><nav><button className={mode==='run'?'active':''} onClick={()=>setMode('run')}>Kit 실행</button><button className={mode==='build'?'active':''} onClick={()=>setMode('build')}>Kit 편집</button><button className={mode==='json'?'active':''} onClick={()=>setMode('json')}>JSON 개발</button></nav></header>
 {mode==='run'?<section className="card"><h1>폼 입력 루틴</h1><p className="muted">Kit JSON의 URL과 루틴을 읽어 {'{{name}}'}, {'{{num}}'}을 실제 값으로 바꿔 실행합니다.</p><label>Kit<select value={file} onChange={e=>setFile(e.target.value)}>{kits.map(k=><option key={k.file} value={k.file}>{k.title}</option>)}</select></label><label>이름<input value={name} onChange={e=>setName(e.target.value)}/></label><label>번호<input value={num} onChange={e=>setNum(e.target.value)} inputMode="numeric"/></label><div className="notice">이름·번호는 이 앱에 저장하지 않습니다. 실제 제출 데이터는 대상 폼의 운영자에게 전달될 수 있습니다.</div><label className="check"><input type="checkbox" checked={agree} onChange={e=>setAgree(e.target.checked)}/> 안내 내용을 확인했습니다.</label><button className="primary" disabled={!agree||!file} onClick={run}>확장 프로그램으로 실행</button><a className="download" href="./download/form-routine-kit-extension.zip" download>Chrome 확장 프로그램 ZIP 다운로드</a><p className="status">{status}</p></section>
 :mode==='build'?<section className="card"><h1>폼을 읽어 Kit 편집</h1><p className="muted">현재 폼의 주관식·객관식·체크박스·동의·버튼을 읽고, 각 항목을 루틴으로 선택합니다.</p><button className="primary" onClick={analyze}>현재 페이지 읽기</button>{analysis&&<div><label>Kit 이름<input value={kitTitle} onChange={e=>setKitTitle(e.target.value)}/></label><label>폼 URL 템플릿<input value={urlTemplate} onChange={e=>setUrlTemplate(e.target.value)} placeholder="https://example.com/form?name={{name}}&num={{num}}"/></label><p className="muted">URL과 답변에서 {'{{name}}'} = 이용자 이름, {'{{num}}'} = 이용자 번호</p><h3>읽어온 문항</h3>{analysis.questions.map(q=><article className="question" key={q.index}><b>{q.question||('문항 '+(q.index+1))}</b><small>{q.choices.length?'객관식/선택':'주관식/입력'} · {q.inputs.map(x=>x.type||x.tag).join(', ')}</small><button onClick={()=>addQuestion(q)}>이 문항 추가</button></article>)}<h3>읽어온 버튼</h3>{analysis.buttons.map((b,i)=><article className="question" key={i}><b>{b.text}</b><small>{b.tag}{b.type?' · '+b.type:''}</small><button onClick={()=>addButton(b)}>다음/제출 동작 추가</button></article>)}<h3>현재 Kit 루틴</h3>{steps.map((s,i)=><article className="question" key={i}><select value={s.type} onChange={e=>updateStep(i,{type:e.target.value as Step['type']})}><option value="choice">객관식</option><option value="checkbox">체크박스</option><option value="agreement">동의</option><option value="text">텍스트</option><option value="name">{'{{name}}'}</option><option value="num">{'{{num}}'}</option><option value="action">다음/제출 버튼</option></select>{s.type==='action'?<><input value={s.text||''} placeholder="버튼 텍스트" onChange={e=>updateStep(i,{text:e.target.value})}/><input value={s.nextUrl||''} placeholder="선택: 다음 URL ({{name}}, {{num}} 가능)" onChange={e=>updateStep(i,{nextUrl:e.target.value})}/></>:<><b>{s.question}</b><input value={s.answer||''} placeholder="답변 또는 {{name}} / {{num}}" onChange={e=>updateStep(i,{answer:e.target.value})}/></>}<button onClick={()=>removeStep(i)}>삭제</button></article>)}<button className="primary" onClick={save}>Kit JSON 저장 / 배포</button></div>}<p className="status">{status}</p></section>
 :<section className="card"><h1>개발자 JSON 편집</h1><p className="muted">웹 편집기에서 만든 Kit를 그대로 확인·수정하거나, 개발자가 JSON을 직접 작성해 불러올 수 있습니다.</p><input type="file" accept=".json,application/json" onChange={importJson}/><textarea className="json-editor" value={raw} onChange={e=>setRaw(e.target.value)} placeholder={'{\n  "version": 3,\n  "title": "내 Kit",\n  "forms": [{ "url": "https://example.com/form?name={{name}}&num={{num}}", "steps": [] }]\n}'}/><button className="primary" onClick={applyRaw}>JSON 불러오기</button><button onClick={()=>{try{setRaw(JSON.stringify(buildJson(),null,2));setStatus('현재 편집 상태를 JSON으로 갱신했습니다.')}catch{}}}>현재 편집 상태 JSON 보기</button><p className="status">{status}</p></section>}</main>
}